it('constants', () => {
  expect(require('./constants')).toMatchInlineSnapshot(`
Object {
  "HANDSHAKE_MSG_TYPE_PROPNAME": "_IPC_REQUEST/HANDSHAKE_MSG_TYPE",
  "HANDSHAKE_REQUEST_MSG": "_IPC_REQUEST/HANDSHAKE_MSG_TYPE:REQUEST",
  "HANDSHAKE_RESPONSE_MSG": "_IPC_REQUEST/HANDSHAKE_MSG_TYPE:RESPONSE",
  "HANDSHAKE_UID_PROPNAME": "_IPC_REQUEST/HANDSHAKE_UID",
  "MSG_TYPE_PROPNAME": "_IPC_REQUEST/MSG_TYPE",
  "PAYLOAD_PROPNAME": "_IPC_REQUEST/PAYLOAD",
  "REQUEST_MSG": "_IPC_REQUEST/MSG_TYPE:REQUEST",
  "RESPONSE_MSG": "_IPC_REQUEST/MSG_TYPE:RESPONSE",
  "UID_PROPNAME": "_IPC_REQUEST/REQUEST_UID",
}
`)
})
