const HANDSHAKE_UID_PROPNAME = '_IPC_REQUEST/HANDSHAKE_UID'
const HANDSHAKE_MSG_TYPE_PROPNAME = '_IPC_REQUEST/HANDSHAKE_MSG_TYPE'
const HANDSHAKE_REQUEST_MSG = '_IPC_REQUEST/HANDSHAKE_MSG_TYPE:REQUEST'
const HANDSHAKE_RESPONSE_MSG = '_IPC_REQUEST/HANDSHAKE_MSG_TYPE:RESPONSE'

const UID_PROPNAME = '_IPC_REQUEST/REQUEST_UID'
const PAYLOAD_PROPNAME = '_IPC_REQUEST/PAYLOAD'

const MSG_TYPE_PROPNAME = '_IPC_REQUEST/MSG_TYPE'
const REQUEST_MSG = '_IPC_REQUEST/MSG_TYPE:REQUEST'
const RESPONSE_MSG = '_IPC_REQUEST/MSG_TYPE:RESPONSE'

module.exports = {
  HANDSHAKE_UID_PROPNAME,
  HANDSHAKE_MSG_TYPE_PROPNAME,
  HANDSHAKE_REQUEST_MSG,
  HANDSHAKE_RESPONSE_MSG,
  UID_PROPNAME,
  PAYLOAD_PROPNAME,
  MSG_TYPE_PROPNAME,
  REQUEST_MSG,
  RESPONSE_MSG
}
